#!/bin/bash

#Get sudo first
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

#Add shortcuts and flavorings to bashrc
#upgrademe alias runs apt update and upgrade together
if (grep -Fq "upgrademe" /home/daniel/.bashrc)
	then
    echo "\"upgrademe\" alias found. Moving on..."
  else
    echo "alias upgrademe=\"sudo bash -c 'apt-get update && apt-get upgrade'\"" >> /home/daniel/.bashrc
fi

#Update and install commonly used software first.
  sudo apt update 
  sudo apt -y upgrade
  
#install apt add repository and the like...
  sudo apt -y install software-properties-common
  
#install snap, bc, bison, flex, libssl-dev, g++, build-essential, 
  sudo apt -y install snapd bc bison flex libssl-dev g++ build-essential
  
#install everything else!
  sudo apt -y install python python3 python-setuptools python3-setuptools pip pip3
  
#Finally add bugfixes and such.
#Killing Chromium doesn't work yet due to Lightdm committing suicide before Chromium gets a chance to die gracefully.
sudo cat >> /etc/init/lightdm.conf <<EOF
pre-stop script
    pkill --oldest chromium
    sleep 2
end script
EOF

dconf load / < mintdconf.conf

#Reboot to finalize changes
sudo reboot
